roughed in thoughts

diff --git a/deploy/01-build-server b/deploy/01-build-server
--- a/deploy/01-build-server
+++ b/deploy/01-build-server
@@ -74,7 +74,9 @@ create_reserved_ip() {
 }
 
 get_reserved_ip(){
-  # TODO there is a potential bugs, where an IP belongs to another service in the same project, or there are more than one IP reserved IP addresses
+  # TODO RESERVED_IP = ASSIGNED IP, but if no ASSIGNED IP then check for an unused RESERVED IP (that was previously allocated)
+  # Can we use DNS root records to inform us of the previously reserved ip, and use that?
+  # Update clean up script to give the option to relinquish a reserved IP, and associated DNS records
   export RESERVED_IP=$(doctl compute reserved-ip list --format IP --no-header | awk '{print $1}')
   export ASSIGNED_IP=$(doctl compute reserved-ip list --format DropletName,IP --no-header | grep "$DIGITAL_OCEAN_SERVER_NAME" | awk '{print $2}')
 }
@@ -89,42 +91,31 @@ update_domains() {
   DOMAINS=${DOMAINS:-""}
 
   # Check that the required environment variables are set
-  if [ -z "$DOMAINS" ] || [ -z "$RESERVED_IP" ]; then
+  if [ -z "$DIGITAL_OCEAN_DOMAIN" ] || [ -z "$RESERVED_IP" ]; then
     echo "ERROR: Both DOMAINS and RESERVED_IP environment variables must be set."
     exit 1
   fi
 
-  for DOMAIN in $(echo $DOMAINS | tr ',' ' '); do
-    
     # Check if the DNS Zone exists for the domain
-    if ! doctl compute domain list $DOMAIN --format "Domain" | grep -q "^$DOMAIN$" ; then 
-      # if not, create it 
-      echo "Creating domain for $DOMAIN"
-      doctl compute domain create $DOMAIN --ip-address $RESERVED_IP
-    fi
+  if ! doctl compute domain list $DIGITAL_OCEAN_DOMAIN --format "Domain" | grep -q "^$DIGITAL_OCEAN_DOMAIN$" ; then 
+    # if not, create it 
+    echo "Creating domain for $DIGITAL_OCEAN_DOMAIN"
+    doctl compute domain create $DIGITAL_OCEAN_DOMAIN --ip-address $RESERVED_IP
+  fi
 
-    export WWW_RECORD_ID=$(doctl compute domain records list $DOMAIN --format "ID,Type,Name,Data" | grep "\sA\s*www\s" | awk '{print $1}') ; 
-    export ROOT_RECORD_ID=$(doctl compute domain records list $DOMAIN --format "ID,Type,Name,Data" | grep "\sA\s*\@\s" | awk '{print $1}') ; 
+  for A_NAME in $(echo $DIGITAL_OCEAN_A_RECORDS | tr ',' ' '); do
 
-    echo WWW RECORD: $WWW_RECORD_ID
-    echo Root Record: $ROOT_RECORD_ID
+    export RECORD_ID=$(doctl compute domain records list $A_NAME --format "ID,Type,Name,Data" | grep "\sA\s*$A_NAME\s" | awk '{print $1}') ; 
+
+    echo A_RECORD: $RECORD_ID
 
     # Check if the www record already exists for the domain
-    if [[ -z "$WWW_RECORD_ID" ]]; then
-      echo "Create A record www for $DOMAIN with $RESERVED_IP"
-      doctl compute domain records create $DOMAIN --record-type A --record-name www --record-data $RESERVED_IP
+    if [[ -z "$RECORD_ID" ]]; then
+      echo "Create A record $A_NAME for $DIGITAL_OCEAN_DOMAIN with $RESERVED_IP"
+      doctl compute domain records create $DIGITAL_OCEAN_DOMAIN --record-type A --record-name $A_NAME --record-data $RESERVED_IP
     else
-      echo "Update A record www for $DOMAIN with $RESERVED_IP"
-      doctl compute domain records update $DOMAIN --record-id $WWW_RECORD_ID --record-data $RESERVED_IP
-    fi
-
-    # Check if the @ record already exists for the domain
-    if [[ -z "$ROOT_RECORD_ID" ]]; then
-      echo "Create A record @ for $DOMAIN with $RESERVED_IP"
-      doctl compute domain records create $DOMAIN --record-type A --record-name @ --record-data $RESERVED_IP
-    else
-      echo "Update A record @ for $DOMAIN with $RESERVED_IP"
-      doctl compute domain records update $DOMAIN --record-id $ROOT_RECORD_ID --record-data $RESERVED_IP
+      echo "Update A record $A_NAME for $DIGITAL_OCEAN_DOMAIN with $RESERVED_IP"
+      doctl compute domain records update $DIGITAL_OCEAN_DOMAIN --record-id $RECORD_ID --record-data $RESERVED_IP
     fi
   done
 }
